version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:latest                            #从私有仓库拉镜像
    restart: always                    
    volumes:
      - ./mysql/data/:/var/lib/mysql/                             #映射mysql的数据目录到宿主机，保存数据
      - ./mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf #把mysql的配置文件映射到容器的相应目录
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5050:5050
      - 4040:4040
    volumes:
      - ./webserver:/webserver
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf            #映射nginx的配置文件到容器里
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/data/:/var/share/nginx/html/                     #映射nginx的网页目录到容器里
    links:
      - tomcat_1                                               #连接 tomcat镜像
  tomcat_1:
    container_name: tomcat_1
    image: tomcat:latest
    restart: always
    ports:
      - 8080:8080
      - 8009:8009
    volumes:
      - ./tomcat/webapps/web:/usr/local/tomcat/webapps/web          #映射一个web服务
      - ./tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml  #映射 tomcat的配置文件到容器里
      - ./tomcat/logs/:/usr/local/tomcat/logs/
    links:
      - mysql                                                   #连接数据库镜像

